### PR TITLE
Update chainparams.cpp

### PR DESCRIPTION
**Pull request by jk14**
Updated dns seed entry.

### CODE REVIEW

**Comment by jk14** [comment]
Gert's request yet, update to: vtc.gertjaap.org

**Comment by metalicjames** [comment]
I only get a response from `useast1.vtconline.org` and `vtc.gertjaap.org` from that list.

**Comment by jk14** [comment]
only seeds with proper response included

**Comment by jk14** [comment]
single commented out line removed

**Comment by jk14** [comment]
Added fresh checkpoint (block no. 1474747)

**Comment by metalicjames** [comment]
@jk14 can you rebase this PR to point to master and squash it into two commits (or two PRs), one updating the DNS seeds and the other adding the new checkpoint?

**Comment by jk14** [comment]
check in master if that is what you need

**Comment by jk14** [comment]
New PR to master branch

**Pull request closed without merging**
