### PR TITLE
backports from upstream 0.21.2

### PR DESCRIPTION
**Pull request by vertiond**

### CODE REVIEW

**Comment by vertiond** [comment]
```
~/github/vertcoin$ find output/ -type f -print0 | sort -z | xargs -r0 sha256sum
a980a11cfcca049c88b1c246660d423b171f103718c6c317cafd83f6d7af7fae  output/src/vertcoin-fb77041e8aa1.tar.gz
3ea41ea160cc4e2e65dd43b2d5928ffbcafb18dea2ed0122447eb43f7dd3ed4b  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu-debug.tar.gz
bab201a096d9effc602da4edb9bc825937eb11125fd03396090d19ee5fd8112d  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu.tar.gz
1e07b6dfb342085141955984f87566eddb86e660aea8d56ba9f0d11ff52661c6  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf-debug.tar.gz
66100f8ff4f346e12d566ef62ed1da3ed21d33a4bd1f53c3f62b6785ea286f6d  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf.tar.gz
3afd460144b379e92935f7e5a76996408059ce894a9c50662eb20506c6e921ae  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu-debug.tar.gz
28afba11e291f456b4f454f36e0e18fadf313e4f60abe1f95a99d01964d7fe79  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu.tar.gz
b97c7c9fb3f8caae38ff6dcf732395c69be25e33f51526fbc46477c38828afcc  output/vertcoin-fb77041e8aa1-win64-debug.zip
53c337eff2bae1478ddef4ac21d6cd25369859781b7632e647ad4660d85c8a7f  output/vertcoin-fb77041e8aa1-win64-setup-unsigned.exe
3c02f6122a5b858f11b1c46ca2ae9081872a76d928604c913f3b5f12e7fc22e9  output/vertcoin-fb77041e8aa1-win64.zip
895ffb0f226dd123bdf91b781d8974e628b97f15fc6b3eeca79adcddde8a1276  output/vertcoin-fb77041e8aa1-win-unsigned.tar.gz
801f205fc7c63889d0b67e1b40685ad431241ca52f560778415d49871dbfa0f5  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu-debug.tar.gz
febf683b2a8e265df9494a0989f75f55d354f3cb2ab61576ca00ec52168592bb  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu.tar.gz
```

**Comment by KforG** [comment]
I have matching checksums
```
kg@KG:~/vertcoin-core$ find output/ -type f -print0 | sort -z | xargs -r0 sha256sum
a980a11cfcca049c88b1c246660d423b171f103718c6c317cafd83f6d7af7fae  output/src/vertcoin-fb77041e8aa1.tar.gz
3ea41ea160cc4e2e65dd43b2d5928ffbcafb18dea2ed0122447eb43f7dd3ed4b  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu-debug.tar.gz
bab201a096d9effc602da4edb9bc825937eb11125fd03396090d19ee5fd8112d  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu.tar.gz
1e07b6dfb342085141955984f87566eddb86e660aea8d56ba9f0d11ff52661c6  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf-debug.tar.gz
66100f8ff4f346e12d566ef62ed1da3ed21d33a4bd1f53c3f62b6785ea286f6d  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf.tar.gz
3afd460144b379e92935f7e5a76996408059ce894a9c50662eb20506c6e921ae  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu-debug.tar.gz
28afba11e291f456b4f454f36e0e18fadf313e4f60abe1f95a99d01964d7fe79  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu.tar.gz
b97c7c9fb3f8caae38ff6dcf732395c69be25e33f51526fbc46477c38828afcc  output/vertcoin-fb77041e8aa1-win64-debug.zip
53c337eff2bae1478ddef4ac21d6cd25369859781b7632e647ad4660d85c8a7f  output/vertcoin-fb77041e8aa1-win64-setup-unsigned.exe
3c02f6122a5b858f11b1c46ca2ae9081872a76d928604c913f3b5f12e7fc22e9  output/vertcoin-fb77041e8aa1-win64.zip
895ffb0f226dd123bdf91b781d8974e628b97f15fc6b3eeca79adcddde8a1276  output/vertcoin-fb77041e8aa1-win-unsigned.tar.gz
801f205fc7c63889d0b67e1b40685ad431241ca52f560778415d49871dbfa0f5  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu-debug.tar.gz
febf683b2a8e265df9494a0989f75f55d354f3cb2ab61576ca00ec52168592bb  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu.tar.gz
```

**Comment by sylvesternumski** [comment]
Looks good to me
```
numski@numski:~/vertcoin-core$ find output/ -type f -print0 | sort -z | xargs -r0 sha256sum
a980a11cfcca049c88b1c246660d423b171f103718c6c317cafd83f6d7af7fae  output/src/vertcoin-fb77041e8aa1.tar.gz
3ea41ea160cc4e2e65dd43b2d5928ffbcafb18dea2ed0122447eb43f7dd3ed4b  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu-debug.tar.gz
bab201a096d9effc602da4edb9bc825937eb11125fd03396090d19ee5fd8112d  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu.tar.gz
1e07b6dfb342085141955984f87566eddb86e660aea8d56ba9f0d11ff52661c6  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf-debug.tar.gz
66100f8ff4f346e12d566ef62ed1da3ed21d33a4bd1f53c3f62b6785ea286f6d  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf.tar.gz
3afd460144b379e92935f7e5a76996408059ce894a9c50662eb20506c6e921ae  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu-debug.tar.gz
28afba11e291f456b4f454f36e0e18fadf313e4f60abe1f95a99d01964d7fe79  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu.tar.gz
895ffb0f226dd123bdf91b781d8974e628b97f15fc6b3eeca79adcddde8a1276  output/vertcoin-fb77041e8aa1-win-unsigned.tar.gz
b97c7c9fb3f8caae38ff6dcf732395c69be25e33f51526fbc46477c38828afcc  output/vertcoin-fb77041e8aa1-win64-debug.zip
53c337eff2bae1478ddef4ac21d6cd25369859781b7632e647ad4660d85c8a7f  output/vertcoin-fb77041e8aa1-win64-setup-unsigned.exe
3c02f6122a5b858f11b1c46ca2ae9081872a76d928604c913f3b5f12e7fc22e9  output/vertcoin-fb77041e8aa1-win64.zip
801f205fc7c63889d0b67e1b40685ad431241ca52f560778415d49871dbfa0f5  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu-debug.tar.gz
febf683b2a8e265df9494a0989f75f55d354f3cb2ab61576ca00ec52168592bb  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu.tar.gz
```

**Comment by cruelnovo** [comment]
```
novo@cruelnovo-build:~/vertcoin-core$ find output/ -type f -print0 | sort -z | xargs -r0 sha256sum
a980a11cfcca049c88b1c246660d423b171f103718c6c317cafd83f6d7af7fae  output/src/vertcoin-fb77041e8aa1.tar.gz
3ea41ea160cc4e2e65dd43b2d5928ffbcafb18dea2ed0122447eb43f7dd3ed4b  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu-debug.tar.gz
bab201a096d9effc602da4edb9bc825937eb11125fd03396090d19ee5fd8112d  output/vertcoin-fb77041e8aa1-aarch64-linux-gnu.tar.gz
1e07b6dfb342085141955984f87566eddb86e660aea8d56ba9f0d11ff52661c6  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf-debug.tar.gz
66100f8ff4f346e12d566ef62ed1da3ed21d33a4bd1f53c3f62b6785ea286f6d  output/vertcoin-fb77041e8aa1-arm-linux-gnueabihf.tar.gz
3afd460144b379e92935f7e5a76996408059ce894a9c50662eb20506c6e921ae  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu-debug.tar.gz
28afba11e291f456b4f454f36e0e18fadf313e4f60abe1f95a99d01964d7fe79  output/vertcoin-fb77041e8aa1-riscv64-linux-gnu.tar.gz
b97c7c9fb3f8caae38ff6dcf732395c69be25e33f51526fbc46477c38828afcc  output/vertcoin-fb77041e8aa1-win64-debug.zip
53c337eff2bae1478ddef4ac21d6cd25369859781b7632e647ad4660d85c8a7f  output/vertcoin-fb77041e8aa1-win64-setup-unsigned.exe
3c02f6122a5b858f11b1c46ca2ae9081872a76d928604c913f3b5f12e7fc22e9  output/vertcoin-fb77041e8aa1-win64.zip
895ffb0f226dd123bdf91b781d8974e628b97f15fc6b3eeca79adcddde8a1276  output/vertcoin-fb77041e8aa1-win-unsigned.tar.gz
801f205fc7c63889d0b67e1b40685ad431241ca52f560778415d49871dbfa0f5  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu-debug.tar.gz
febf683b2a8e265df9494a0989f75f55d354f3cb2ab61576ca00ec52168592bb  output/vertcoin-fb77041e8aa1-x86_64-linux-gnu.tar.gz
```

**Pull request closed without merging**
